### ISSUE TITLE
Wrong Value in Ressource

### ISSUE THREAD

**Issue by Red13Posh** [kennyvh/UpdateServicesClientDSC#1]
Hallo, I find a mistake in the DSC Ressource.
In the line 
> (Get-UpdateOption).Value -eq '4'

the function give back this.

> AutoUpdateOption |  RegistryPath                                                           
> AutoDownloadAndScheduleInstallation | HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU

There is no Value "4". The result is that the Ressource ever have the result:
> Write-Error 'This only works if Update Option is set to AutoDownloadAndScheduleInstallation'

I have correct this place like this:
> if ((Get-UpdateOption).AutoUpdateOption -eq 'AutoDownloadAndScheduleInstallation') 

Then all is O.K.

Best regards
Andreas Raschke

**Comment by Earlyflash** [comment]
I agree - I'm having the exact same problem with my configuration with the same issue.

**Comment by kennyvh** [comment]
@Red13Posh  You're right 👍. I will check the pull requests of @paulhaigh and update the module on the PSGallery.
