### ISSUE TITLE
ScheduledInstallDay can have value 0

### ISSUE THREAD

**Issue by Earlyflash** [kennyvh/UpdateServicesClientDSC#2]
Hi

According to here:
https://msdn.microsoft.com/en-us/library/dd939844(v=ws.10).aspx

The regkey for ScheduledInstallDay can have value '0', which maps to 'All' days.

This would be really useful.

I'd make a pull request and fix it (I see the code changes I think), but I'm not clear on how to do this (new to github).

paul

**Comment by Earlyflash** [comment]
I've added a pull request for this code change - please let me know if I did something wrong.

It's important to get the base repository changed to add this, as when using the module in Azure DSC we can't update the module directly.

**Comment by kennyvh** [comment]
@paulhaigh I have merged your pull request and updated the module in the PowerShell Gallery. thnx! 👍
